/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.lang.StringBuilder;

/**
 *
 * @author matwa
 */
public class ClientGUI extends javax.swing.JFrame {

    public Client client;
    public boolean serverConnection = false;
    private final String IP_ADDRESS = "127.0.0.1";
    private final int PORT = 5012;
    private Client[] clients;
    private StringBuilder sb = new StringBuilder();

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        initListeners();
        System.out.println(serverConnection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        dateButton = new javax.swing.JButton();
        uptimeButton = new javax.swing.JButton();
        memoryButton = new javax.swing.JButton();
        netstatButton = new javax.swing.JButton();
        curuserButton = new javax.swing.JButton();
        processesButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        connectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numClients = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        moreInfoBut = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CNT4504 Project 1");
        setResizable(false);

        dateButton.setText("Date");

        uptimeButton.setText("Uptime");

        memoryButton.setText("Memory Use");

        netstatButton.setText("Netstat");

        curuserButton.setText("Current Users");

        processesButton.setText("Running Processes");

        quitButton.setText("Quit");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Server Response:");

        numClients.setValue(1);

        jLabel2.setText("Num. of Clients:");

        moreInfoBut.setText("View Info");
        moreInfoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreInfoButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(processesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(memoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curuserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(netstatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uptimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(moreInfoBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numClients, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateButton)
                        .addGap(18, 18, 18)
                        .addComponent(uptimeButton)
                        .addGap(18, 18, 18)
                        .addComponent(memoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(netstatButton)
                        .addGap(18, 18, 18)
                        .addComponent(curuserButton)
                        .addGap(18, 18, 18)
                        .addComponent(processesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moreInfoBut)
                        .addGap(18, 18, 18)
                        .addComponent(quitButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(numClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectButtonActionPerformed

    private void moreInfoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreInfoButActionPerformed
        JOptionPane.showMessageDialog(this, 
                "      Created by:\nLiam Clarke\nKaleb LaBarrie\nTrang Nguyen\nWilliam Mejia\nMichael Turner\nMathew Waroff", 
                "CNT4504 Project1 - Team 4",
                JOptionPane.PLAIN_MESSAGE);
        //Created by:\nLiam Clarke\nKaleb LaBarrie\nTrang Nguyen\nWilliam Mejia\nMichael Turner\nMathew Waroff
    }//GEN-LAST:event_moreInfoButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    
    private void controlButtons(boolean status){
        dateButton.setEnabled(status);
        uptimeButton.setEnabled(status);
        memoryButton.setEnabled(status);
        netstatButton.setEnabled(status);
        curuserButton.setEnabled(status);
        processesButton.setEnabled(status);
        
    }
    public void initListeners() {
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent) {
                System.exit(0);
            }
        });
        controlButtons(false);
        
        dateButton.addActionListener(new ButtonClickListener());
        uptimeButton.addActionListener(new ButtonClickListener());
        memoryButton.addActionListener(new ButtonClickListener());
        netstatButton.addActionListener(new ButtonClickListener());
        curuserButton.addActionListener(new ButtonClickListener());
        processesButton.addActionListener(new ButtonClickListener());
        quitButton.addActionListener(new ButtonClickListener());
        connectButton.addActionListener(new ButtonClickListener());
    }

    private class ButtonClickListener implements ActionListener {
        public void actionPerformed(ActionEvent e){
            String command = e.getActionCommand();
            try {
                switch (command) {
                    case "Connect":
                        System.out.println("connecting to server");
                        runManyClients();
                        numClients.setEnabled(false);
                        connectButton.setText("Disconnect");
                        controlButtons(true);
                        break;
                    case "Disconnect":
                        System.out.println("disconnecting");
                        jTextArea1.setText("Disconnected");
                        closeClients();
                        numClients.setEnabled(true);
                        connectButton.setText("Connect");
                        controlButtons(false);
                        break;
                    case "Date":
                        sb.setLength(0);
                        runManyCommands("date");
                        jTextArea1.setText(sb.toString());
                        break;
                    case "Uptime":
                        sb.setLength(0);
                        runManyCommands("uptime");
                        jTextArea1.setText(sb.toString());
                        break;
                    case "Memory Use":
                        sb.setLength(0);
                        runManyCommands("memory");
                        jTextArea1.setText(sb.toString());
                        break;
                    case "Netstat":
                        sb.setLength(0);
                        runManyCommands("netstat");
                        jTextArea1.setText(sb.toString());
                        break;
                    case "Current Users":
                        sb.setLength(0);
                        runManyCommands("users");
                        jTextArea1.setText(sb.toString());
                        break;
                    case "Running Processes":
                        sb.setLength(0);
                        runManyCommands("processes");
                        jTextArea1.setText(sb.toString());
                        break;
                    case "Quit":
                        System.exit(0);
                        break;
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void runManyClients() {
        int num = (Integer) numClients.getValue();
        clients = new Client[num];
        try{
            if (client != null) {
                client.userInput("close");
            }
            for(int i = 0; i < num; i++) {
                clients[i] = new Client(IP_ADDRESS, PORT);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void runManyCommands(String command){
        try{
            for(Client client : clients){
                sb.append(client.userInput(command) + "\n\n");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    private void closeClients(){
        try{
            for(Client c : clients){
                c.userInput("close");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JButton curuserButton;
    private javax.swing.JButton dateButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton memoryButton;
    private javax.swing.JButton moreInfoBut;
    private javax.swing.JButton netstatButton;
    private javax.swing.JSpinner numClients;
    private javax.swing.JButton processesButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton uptimeButton;
    // End of variables declaration//GEN-END:variables
}
